#!/usr/bin/env python3
"""research-quality-footer.py — render the Phase 6 research-method footer
and the matching transcript echo.

Input: JSON on stdin with the aggregated quality signals:
  {
    "market": "dach",                          # market code
    "authority_domains_cited": ["fraunhofer.de", ...],  # union across researchers
    "sub_questions": 5,                        # number of sub-questions researched
    "local_documents": 8,                      # total documents analyzed (0 if no local channel)
    "local_strongly_matched": 1,               # docs that matched the topic strongly
    "wiki_pages": 12,                          # wiki pages consulted (0 if no wiki channel)
    "wiki_instances": ["insight-wave"]         # wiki slugs consulted
  }

Modes:
  markdown   — the "## Research method" section to append to output/report.md
  echo       — short multi-line block for the Phase 6 transcript summary
  json       — structured combination of input + market lookup

Leans on market-summary.summarize() so market name, domain count, query
language phrase all come from the same data source as every other surface.
Stdlib only.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import importlib.util

_spec = importlib.util.spec_from_file_location(
    "market_summary", str(Path(__file__).resolve().parent / "market-summary.py")
)
_ms = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_ms)


def render_echo(signals, market):
    cited = signals.get("authority_domains_cited", []) or []
    total = market["authority_count"]
    shown = cited[:4]
    shown_str = ", ".join(shown) if shown else "(none matched yet)"
    tail = f" (+{len(cited) - len(shown)} more)" if len(cited) > len(shown) else ""
    lines = [
        "Research quality:",
        f"  Market: {market['name']} — {len(cited)} of {total} curated authority domains cited ({shown_str}{tail})",
        f"  Query languages: {market['query_languages_phrase']} across "
        f"{signals.get('sub_questions', 0)} sub-questions",
    ]
    local = signals.get("local_documents", 0) or 0
    if local:
        strong = signals.get("local_strongly_matched", 0) or 0
        lines.append(
            f"  Local documents: {local} analyzed"
            + (f" ({strong} matched the topic strongly)" if strong else "")
        )
    wiki = signals.get("wiki_pages", 0) or 0
    if wiki:
        instances = signals.get("wiki_instances", []) or []
        inst_str = f" from {', '.join(instances)}" if instances else ""
        lines.append(f"  Wiki pages: {wiki} consulted{inst_str}")
    return "\n".join(lines)


def render_markdown(signals, market):
    cited = signals.get("authority_domains_cited", []) or []
    shown = cited[:6]
    shown_str = ", ".join(shown) if shown else "none directly cited in this pass"
    cited_tail = (
        f" (and {len(cited) - len(shown)} more)" if len(cited) > len(shown) else ""
    )
    regs = market.get("regulatory_bodies", []) or []
    reg_shown = regs[:4]
    reg_tail = (
        f" (and {len(regs) - len(reg_shown)} more)" if len(regs) > len(reg_shown) else ""
    )

    parts = []
    parts.append("## Research method")
    parts.append("")
    parts.append(
        f"This report was generated by cogni-research against the **{market['name']}** "
        f"market profile. Queries ran with {market['query_languages_phrase']} across "
        f"{signals.get('sub_questions', 0)} sub-questions."
    )
    parts.append("")
    parts.append(
        f"Source selection was boosted toward **{market['authority_count']} curated "
        f"authority domains** for the region — of those, "
        f"**{len(cited)} contributed to this report** ({shown_str}{cited_tail})."
    )
    if reg_shown:
        parts.append("")
        parts.append(f"Regulatory bodies tracked for this market: {', '.join(reg_shown)}{reg_tail}.")

    local = signals.get("local_documents", 0) or 0
    wiki = signals.get("wiki_pages", 0) or 0
    extra_channels = []
    if local:
        strong = signals.get("local_strongly_matched", 0) or 0
        extra_channels.append(
            f"{local} local documents were analyzed"
            + (f" ({strong} matched the topic strongly)" if strong else "")
        )
    if wiki:
        instances = signals.get("wiki_instances", []) or []
        inst_str = f" from {', '.join(instances)}" if instances else ""
        extra_channels.append(f"{wiki} wiki pages were consulted{inst_str}")
    if extra_channels:
        parts.append("")
        parts.append(
            "In addition to web research, " + " and ".join(extra_channels) + "."
        )

    if market.get("composite_markets"):
        parts.append("")
        parts.append(
            "This is a composite market profile — per-country researchers ran for: "
            + ", ".join(market["composite_markets"]) + "."
        )

    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Render research-quality footer/echo.")
    parser.add_argument(
        "--mode", choices=["markdown", "echo", "json"], required=True
    )
    args = parser.parse_args()

    try:
        signals = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"stdin must be valid JSON: {e}", file=sys.stderr)
        sys.exit(2)

    market_code = signals.get("market") or "_default"
    try:
        data = _ms.load_market_sources()
    except Exception as e:
        print(f"failed to load market-sources.json: {e}", file=sys.stderr)
        sys.exit(1)
    market = _ms.summarize(market_code, data)

    if args.mode == "markdown":
        print(render_markdown(signals, market))
    elif args.mode == "echo":
        print(render_echo(signals, market))
    elif args.mode == "json":
        print(json.dumps(
            {"success": True, "data": {"signals": signals, "market": market}, "error": None},
            ensure_ascii=False,
        ))


if __name__ == "__main__":
    main()
